stages:
  - deploy

deploy-job:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - apt-get update && apt-get install -y awscli
  script:
    - aws eks update-kubeconfig --region us-east-1 --name mlops-cluster
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
    - kubectl rollout status deployment/mlops-model
