apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-model
  template:
    metadata:
      labels:
        app: mlops-model
    spec:
      containers:
      - name: mlops-container
        image: <your_dockerhub_or_ghcr_repo>/mlops-electricity-demand:latest
        ports:
        - containerPort: 8000
