name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install -r ml/requirements.txt
    - run: pytest ci/tests/
    - run: docker build -t ghcr.io/${{ github.actor }}/mlops-electricity-demand:latest .
    - run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.actor }}/mlops-electricity-demand:latest
